services:
  - type: web
    name: medical-diagnosis
    env: python
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: cd doctor && gunicorn doctor.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: medical-diagnosis.onrender.com,localhost,127.0.0.1
