# Generated by Django 4.2 on 2026-06-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
